### ISSUE TITLE
discord terminal theme 

### ISSUE THREAD

**Issue by ff6f8d68** [ff6f8d68/minecord-issues#1]
```css


/* Font Face for Terminal */


/* Import main CSS and CRT effect */
@import url('https://B4T3S.github.io/Fallout4TerminalTheme/mainRewrite.css');
/* ^ This is the main Import ^ DO NOT TOUCH. Without this, the theme won't load!!! */

@import url('https://B4T3S.github.io/Fallout4TerminalTheme/css/crtEffect.css');
/* ^ This is the CRT effect. ^ If you don't like it, remove or comment out this line! */
@font-face {
    font-family: 'Terminal';
    src: url('https://s3-us-west-2.amazonaws.com/s.cdpn.io/86186/terminal_copy.ttf') format('truetype');
}
/* CUSTOMIZE COLORS IN HERE! */
:root,
.theme-dark,
.theme-light {
  --rgb-highlight: 74, 239, 152; /* The main highlight color */
  --rgb-background: 0, 9, 0; /* The main background color */
  --rgb-text: 74, 239, 152; /* The color (almost) all text should use */
  --rgb-close-button: 212, 18, 39; /* The main "close this" or "deny" color */
  --rgb-online-color: 57, 255, 20; /* The color used in the "online" user status symbol */
  --rgb-afk-color: 255, 255, 51; /* The color used in the "idle" user status symbol */
  --rgb-dnd-color: 255, 0, 0; /* The color used in the "do not disturb" user status symbol */
  --rgb-streaming-color: 188, 19, 254; /* The color used in the "streaming X" user status symbol */

  --transition-time: .3s; /* How fast animations added by the theme happen. Default is 0.3 seconds */

  --background-image: unset; /* To add an image, replace unset with url(https://www.YOUR-URL-HERE.com) */
  --background-position: center; /* Positions the background image */
  --background-size: cover; /* Scales the background image */
  --background-blur: 5px; /* Blurs the image which usually helps with readability of text in front of it */
  --background-brightness: 100%; /* Changes the background images brightness */
 
  --show-original-title: 0; /* Whether you want to show Discord's original title (0 means no, 1 means yes) */
  --show-custom-title: 1; /* Whether you want to show a custom title (0 means no, 1 means yes) */
  --custom-title-font-size: 16px; /* The size in pixels of the custom title text */
  --custom-title-font-weight: bold; /* The font "weight" of the custom title text. For reference: https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight */
  --custom-title-margin-top: 0px; /* The distance from the top of the window to the custom title text */
  --custom-title-margin-left: 0px; /* The distance from the left side of the window to the custom title text */
}

/* Apply terminal font to body and specific elements */
body, 
.theme-dark, 
.theme-light {
    font-family: 'Terminal', monospace; /* Apply terminal font throughout */
    color: rgb(var(--rgb-text)); /* Use defined text color */
    background-color: rgb(var(--rgb-background)); /* Use defined background color */
}

h1, h2, h3, .command, .input {
    font-family: 'Terminal', monospace; /* Ensure headers and command text use the terminal font */
}

/* Additional custom styles for the terminal effect */
.command {
    font-size: 20px; /* Adjust command text size */
    line-height: 1.5; /* Set line spacing */
    color: rgb(var(--rgb-text)); /* Text color */
}

.input {
    color: rgb(var(--rgb-text)); /* Input text color */
    outline: none; /* Remove outline */
    background: transparent; /* Transparent background */
    border: none; /* No border */
    font-family: 'Terminal', monospace; /* Terminal font for input */
    font-size: 20px; /* Input text size */
}
```
